Repository wyndchyme/mc3ds-modern, pull requests merged in 2024-12, with the labels that each got.

#19 Add Mod "Compatibility" List
  docs/README.md
Labels: documentation

#20 Add new villagers models
  resourcepacks/vanilla/client/models/mobs.bjson
  resourcepacks/vanilla/client/textures/entity/illager/evoker.3dst
  resourcepacks/vanilla/client/textures/entity/villager/butcher.3dst
  resourcepacks/vanilla/client/textures/entity/villager/farmer.3dst
  resourcepacks/vanilla/client/textures/entity/villager/librarian.3dst
  resourcepacks/vanilla/client/textures/entity/villager/priest.3dst
  resourcepacks/vanilla/client/textures/entity/villager/smith.3dst
  resourcepacks/vanilla/client/textures/entity/villager/villager.3dst
Labels: enhancement

#16 1.7.0 Release Candidate 1
  docs/README.md
  shaders/3DS/dummy
Labels: 1.7.0 "Baroque"

#25 Sync 1.7.0-baroque with main
  credits/credits.txt
  docs/README.md
  docs/uureadme.txt
  resourcepacks/candy/textures/entity/illager/evoker.3dst
  resourcepacks/candy/textures/entity/villager/librarian.3dst
  resourcepacks/candy/textures/entity/villager/priest.3dst
  resourcepacks/cartoon/textures/entity/illager/evoker.3dst
  resourcepacks/city/textures/entity/illager/evoker.3dst
  resourcepacks/fantasy/textures/entity/illager/evoker.3dst
  resourcepacks/festive/textures/entity/illager/evoker.3dst
  resourcepacks/mario/textures/entity/illager/evoker.3dst
  resourcepacks/natural/textures/entity/illager/evoker.3dst
  resourcepacks/plastic/textures/entity/illager/evoker.3dst
  resourcepacks/steampunk/textures/entity/illager/evoker.3dst
Labels: 1.7.0 "Baroque"

#15 2.0.0 Release Candidate 1
  docs/README.md
  shaders/3DS/dummy
  shaders/3DS/placeholder
Labels: 2.0.0 "Romantic"

#28 Add appConfiguration.info for megapack updater
  appConfiguration.info
Labels: enhancement, 2.0.0 "Romantic"

#29 Begin to modernize villagers, add random texture rotation to certain blocks
  docs/CONTRIBUTING.md
  resourcepacks/vanilla/client/blocks.json
  resourcepacks/vanilla/server/entities/villager.json
  resourcepacks/vanilla/server/loot_tables/entities/bat.json
  resourcepacks/vanilla/server/trading/armorer_trades.json
  resourcepacks/vanilla/server/trading/butcher_trades.json
  resourcepacks/vanilla/server/trading/cartographer_trades.json
  resourcepacks/vanilla/server/trading/cleric_trades.json
  resourcepacks/vanilla/server/trading/farmer_trades.json
  resourcepacks/vanilla/server/trading/fisherman_trades.json
  resourcepacks/vanilla/server/trading/fletcher_trades.json
  resourcepacks/vanilla/server/trading/leather_worker_trades.json
  resourcepacks/vanilla/server/trading/librarian_trades.json
  resourcepacks/vanilla/server/trading/shepherd_trades.json
  resourcepacks/vanilla/server/trading/tool_smith_trades.json
  resourcepacks/vanilla/server/trading/weapon_smith_trades.json
Labels: bug, enhancement, 2.0.0 "Romantic"

#32 Sync 2.0.0-romantic with main
  docs/README.md
Labels: 2.0.0 "Romantic"

#34 Sync 2.0.0-romantic with main
  credits/credits.txt
  docs/uureadme.txt
Labels: 2.0.0 "Romantic"

#37 Sync 2.0.0-romantic with main
  notes/patch.txt
Labels: 2.0.0 "Romantic"

#41 Add Pillagers + Outpost to charts
  docs/README.md
Labels: enhancement, 2.0.0 "Romantic"
