Repository wyndchyme/mc3ds-modern, pull requests merged in 2025-01, with the labels that each got.

#45 New sounds.bjson and door sound files
  sounds/random/door_close1.fsb
  sounds/random/door_close2.fsb
  sounds/random/door_close3.fsb
  sounds/random/door_open1.fsb
  sounds/random/door_open2.fsb
  sounds/sounds.bjson
Labels: enhancement, 2.0.0 "Romantic"

#46 Add map fix for stronghold library loot
  resourcepacks/vanilla/server/loot_tables/chests/stronghold_library.json
Labels: enhancement, 2.0.0 "Romantic"

#48 Compatibility List for MC3DS TV - Add to v2.0.0 release
  docs/README.md
Labels: documentation, 2.0.0 "Romantic"

#49 Sync 2.0.0-romantic with main
  resourcepacks/candy/textures/entity/witch.3dst
Labels: 2.0.0 "Romantic"

#50 Sync 2.0.0-romantic with main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 2.0.0 "Romantic"

#52 Add application configuration scripts
  _scripts/README.MD
  _scripts/addNumbersToAppConf.py
  _scripts/generateBaseHashList.py
  _scripts/getAllFileList.py
  _scripts/hashlist.sha256
  _scripts/reitterateHashListAndVersionNumber.py
  appConfiguration.info
Labels: documentation, enhancement

#55 Add Pillager/Vindicator outpost
  structures/igloo/igloo_top_no_trapdoor.nbt
Labels: enhancement, 2.0.0 "Romantic"

#56 Sync 2.0.0-romantic with main
  structures/igloo/igloo_top_no_trapdoor.nbt
Labels: 2.0.0 "Romantic"
