Repository wyndchyme/mc3ds-modern, pull requests merged in 2025-05, with the labels that each got.

#94 port new clouds and carrot behavour to Modernization Megapack
  docs/README.md
  resourcepacks/vanilla/client/textures/environment/clouds.3dst
  resourcepacks/vanilla/server/entities/donkey.json
  resourcepacks/vanilla/server/entities/horse.json
  resourcepacks/vanilla/server/entities/mule.json
  resourcepacks/vanilla/server/entities/sheep.json
  resourcepacks/vanilla/server/loot_tables/entities/vindication_illager.json
Labels: enhancement, 2.3.0 "Shelley"

#96 Update README.md
  docs/README.md
Labels: documentation, 2.3.0 "Shelley"

#97 Fix infamous cloud bug
  shaders/3DS/cloud.shbin
  shaders/3DS/sky.shbin
Labels: enhancement, 2.3.0 "Shelley"

#98 Remove json cleaning from patch note
  notes/patch.txt
Labels: documentation, 2.3.0 "Shelley"

#101 2.3.0 Release Candidate 2
  credits/credits.txt
Labels: 2.3.0 "Shelley"
