Repository wyndchyme/mc3ds-modern, pull requests merged in 2025-02, with the labels that each got.

#58 Fix villager model z fighting
  resourcepacks/vanilla/client/models/mobs.bjson
Labels: enhancement, 2.0.0 "Romantic"

#59 2.1 austen release - java parity fixes
  README.md
  resourcepacks/vanilla/server/entities/blaze.json
  resourcepacks/vanilla/server/entities/creeper.json
  resourcepacks/vanilla/server/entities/husk.json
  resourcepacks/vanilla/server/entities/zombie_villager.json
Labels: bug, enhancement, 2.1.0 "Austen"

#61 optimize loot tables, and undo zillager parity change
  resourcepacks/vanilla/server/entities/boat.json
  resourcepacks/vanilla/server/entities/llama.json
  resourcepacks/vanilla/server/entities/mooshroom.json
  resourcepacks/vanilla/server/entities/ocelot.json
  resourcepacks/vanilla/server/entities/polar_bear.json
  resourcepacks/vanilla/server/entities/silverfish.json
  resourcepacks/vanilla/server/entities/wolf.json
  resourcepacks/vanilla/server/entities/zombie_horse.json
  resourcepacks/vanilla/server/entities/zombie_husk.json
  resourcepacks/vanilla/server/entities/zombie_villager.json
  resourcepacks/vanilla/server/loot_tables/gameplay/fishing/fish.json
Labels: bug, enhancement, 2.1.0 "Austen"

#63 new sheep colour system from latest spring drop preview/snapshot
  resourcepacks/vanilla/server/entities/sheep.json
Labels: enhancement, 2.1.0 "Austen"

#65 Updated patch so compatible with ips patches
  README.md
  code.bps
Labels: enhancement, 2.1.0 "Austen"

#68 Port changes from 25w08a (latest snapshot)
  atlas/atlas.items.meta_79954554_0.3dst
  resourcepacks/vanilla/server/entities/sheep.json
Labels: enhancement, 2.1.0 "Austen"
